Repository Passtival/Passtival-server, pull requests merged in 2025-08, with the labels that each got.

#7 프로젝트 폴더 구조 초기 설정
  backend/src/main/java/com/passtival/backend/domain/festival/booth/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/festival/core/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/festival/menu/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/festival/performance/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/phoneMatch/login/config/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/phoneMatch/login/kakao/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/phoneMatch/meeting/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/raffle/.gitkeep
  backend/src/main/java/com/passtival/backend/global/entity/.gitkeep
  backend/src/main/java/com/passtival/backend/global/error/code/.gitkeep
  backend/src/main/java/com/passtival/backend/global/error/dto/.gitkeep
  backend/src/main/java/com/passtival/backend/global/error/exception/.gitkeep
  backend/src/main/java/com/passtival/backend/global/handler/.gitkeep
  backend/src/main/java/com/passtival/backend/global/swagger/.gitkeep
Labels: 👨🏻‍💻 원진, 📌 Chore, 🥇 높음

#11 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: 🐛 Bug, 👨🏻‍💻준선, 🚀 CI/CD

#13 refactor: deploy.yml 변경
  .github/workflows/deploy.yml
  backend/run.sh
Labels: ✨ Feature, 🐛 Bug, 👨🏻‍💻준선, 🚀 CI/CD, 🥇 높음

#14 Deploy
  .github/workflows/deploy.yml
  backend/run.sh
Labels: 👨🏻‍💻준선, 🚀 CI/CD, 🥇 높음

#25 feat: Swagger 기능
  backend/build.gradle
  backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java
  backend/src/main/java/com/passtival/backend/global/error/exception/.gitkeep
  backend/src/main/java/com/passtival/backend/global/swagger/OpenApiConfig.java
Labels: ✨ Feature, 👨🏻‍💻준선, 🥈 보통

#27 feat: 전역 예외처리
  backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java
  backend/src/main/java/com/passtival/backend/domain/raffle/service/PrizeService.java
  backend/src/main/java/com/passtival/backend/domain/raffle/service/RaffleService.java
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
  backend/src/main/java/com/passtival/backend/global/error/code/.gitkeep
  backend/src/main/java/com/passtival/backend/global/error/dto/.gitkeep
  backend/src/main/java/com/passtival/backend/global/exception/BaseException.java
  backend/src/main/java/com/passtival/backend/global/handler/.gitkeep
  backend/src/main/java/com/passtival/backend/global/handler/GlobalExceptionHandler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: ✨ Feature, 👨🏻‍💻준선, 🥈 보통

#33 refactor: 공연 API 수정
  .github/PULL_REQUEST_TEMPLATE.md
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/entity/Performance.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/entity/Song.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/response/PerformanceDetailResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/response/PerformanceResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/response/SongResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/repository/PerformanceRepository.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/seeder/PerformanceDevSeeder.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/service/PerformanceService.java
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
  backend/src/main/resources/application-dev.yml
Labels: ✨ Feature, 👨🏻‍💻 재상, 🥇 높음

#38 feat: 부스 & 메뉴 목록 조회 API
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/entity/Booth.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothDetailResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/repository/BoothRepository.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/seeder/BoothMenuDevSeeder.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/service/BoothService.java
  backend/src/main/java/com/passtival/backend/domain/festival/core/.gitkeep
  backend/src/main/java/com/passtival/backend/domain/festival/menu/model/entity/Menu.java
  backend/src/main/java/com/passtival/backend/domain/festival/menu/model/response/MenuResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/entity/Performance.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/seeder/PerformanceDevSeeder.java
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
Labels: ✨ Feature, 🛠️ Refactor

#52 feat: 분실물 조회 API
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/model/response/FoundItemResponse.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/service/LnfService.java
Labels: ✨ Feature, 👨🏻‍💻준선, 🥇 높음

#54 24/feature/performance api
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/response/CursorPageResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/repository/PerformanceRepository.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/seeder/PerformanceDevSeeder.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/service/PerformanceService.java
Labels: ✨ Feature, 👨🏻‍💻 재상

#56 53/refactor/lnf create
  backend/src/main/java/com/passtival/backend/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/com/passtival/backend/domain/authentication/repository/AuthenticationKeyRepository.java
  backend/src/main/java/com/passtival/backend/domain/authentication/service/AuthenticationService.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/model/request/FoundItemRequest.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/service/LnfService.java
  backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java
  backend/src/main/java/com/passtival/backend/domain/raffle/service/RaffleService.java
Labels: ✨ Feature, 👨🏻‍💻준선, 🛠️ Refactor, 🥇 높음

#57 35/feat/booth menu api
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
Labels: 👨🏻‍💻 재상, 🛠️ Refactor

#61 feat: 검증키로 인증 후 데이터 저장 API (공연데이터 삽입)
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceSeedController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/request/PerformanceRequest.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/repository/PerformanceRepository.java
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
Labels: ✨ Feature, 👨🏻‍💻 재상

#64 feat: 검증키로 인증 후 데이터 저장 API (부스 & 메뉴 데이터 삽입)
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothSeedController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/request/BoothRequest.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/repository/BoothRepository.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/seeder/BoothMenuDevSeeder.java
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
Labels: ✨ Feature, 👨🏻‍💻 재상, 🛠️ Refactor

#65 fix: 인증키 공통설정파일 수정 & 공통응답으로 수정
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothSeedController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceSeedController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: ⚙️ Setting, 👨🏻‍💻 재상, 🛠️ Refactor

#66 fix: 공연이름으로 조회 -> id로 조회 #24
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/response/PerformanceDetailResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/repository/PerformanceRepository.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/service/PerformanceService.java
Labels: 👨🏻‍💻 재상, 🛠️ Refactor

#67 fix: 부스이름으로 조회 -> id로 조회 #35
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothDetailResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/service/BoothService.java
Labels: 👨🏻‍💻 재상, 🛠️ Refactor

#71 refactor: PresignURL 파일명, 확장자 형식 추가 #70 to dev
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java
Labels: 👨🏻‍💻준선, 🛠️ Refactor

#74 refactor: profiles 인자 제거 #73 to dev
  backend/src/main/resources/application.yml
Labels: 👨🏻‍💻준선, 🛠️ Refactor

#72 Feat: 관리자 커스텀 로그인 추가 + 필터 예외처리 #63 to dev
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/AdminAuthController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/initializer/AdminInitializer.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/model/entity/Admin.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/model/request/AdminLoginRequest.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/repository/AdminRepository.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/service/AdminAuthService.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/test/AuthTestController.java
  backend/src/main/java/com/passtival/backend/global/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/passtival/backend/global/auth/filter/LoginFilter.java
  backend/src/main/java/com/passtival/backend/global/auth/handler/CustomAuthenticationFailureHandler.java
  backend/src/main/java/com/passtival/backend/global/auth/handler/OAuth2SuccessHandler.java
  backend/src/main/java/com/passtival/backend/global/auth/service/AuthService.java
  backend/src/main/java/com/passtival/backend/global/auth/service/CustomMemberDetailsService.java
  backend/src/main/java/com/passtival/backend/global/auth/service/CustomOAuth2UserService.java
  backend/src/main/java/com/passtival/backend/global/auth/service/OAuth2SuccessHandler.java
  backend/src/main/java/com/passtival/backend/global/auth/util/JwtUtil.java
  backend/src/main/java/com/passtival/backend/global/auth/util/ResponseUtil.java
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: ✨ Feature, 👨🏻‍💻 원진, 🥇 높음

#77 관리자 권한 도입 후, 분실물 인증키 로직 제거, Swagger 가독성 개선 #75,#76 to dev
  backend/src/main/java/com/passtival/backend/domain/authentication/controller/AuthenticationController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothSeedController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceSeedController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/AdminAuthController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/service/LnfService.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MatchingController.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MemberController.java
  backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java
  backend/src/main/java/com/passtival/backend/global/auth/controller/AuthController.java
Labels: 👨🏻‍💻준선, 🛠️ Refactor, 🥇 높음

#79 fix: 삽입데이터 introduction, imagePath 추가 & refactor데이터 삽입 DTO 제약조건 고도화
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothSeedController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/request/BoothRequest.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/model/request/PerformanceRequest.java
Labels: 👨🏻‍💻 재상, 🛠️ Refactor

#84 feat: 소셜 로그인의 리다이렉트 구현
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MemberLoginController.java
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
Labels: ✨ Feature, 👨🏻‍💻 원진, 🥇 높음

#93 Refactor: lnf에서 S3 기능 S3(global)로 적재 #92
  backend/src/main/java/com/passtival/backend/domain/lostfound/controller/LnfController.java
  backend/src/main/java/com/passtival/backend/domain/lostfound/service/LnfService.java
  backend/src/main/java/com/passtival/backend/global/s3/controller/S3Controller.java
  backend/src/main/java/com/passtival/backend/global/s3/service/S3Service.java
Labels: 👨🏻‍💻준선, 🛠️ Refactor, 🥇 높음

#90 Refactor: Member 확장성을 고려해서 소셜로그인 분리 및 엔드포인트 수정
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MatchingApplicantController.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MatchingController.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/test/AuthTestController.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/test/MatchingTestController.java
  backend/src/main/java/com/passtival/backend/domain/matching/model/entity/MatchingApplicant.java
  backend/src/main/java/com/passtival/backend/domain/matching/model/request/MatchingApplicantPatchRequest.java
  backend/src/main/java/com/passtival/backend/domain/matching/model/response/MatchingApplicantResponse.java
  backend/src/main/java/com/passtival/backend/domain/matching/repository/MatchingApplicantRepository.java
  backend/src/main/java/com/passtival/backend/domain/matching/service/MatchingApplicantService.java
  backend/src/main/java/com/passtival/backend/domain/matching/service/MatchingScheduler.java
  backend/src/main/java/com/passtival/backend/domain/matching/service/MatchingService.java
  backend/src/main/java/com/passtival/backend/domain/member/controller/MemberController.java
  backend/src/main/java/com/passtival/backend/global/auth/model/CustomMemberDetails.java
  backend/src/main/java/com/passtival/backend/global/auth/service/CustomMemberDetailsService.java
  backend/src/main/java/com/passtival/backend/global/auth/service/CustomOAuth2UserService.java
Labels: 👨🏻‍💻 원진, 🛠️ Refactor, 🥇 높음

#95 Refactor: 상품 관련 로직 분리 #94
  backend/src/main/java/com/passtival/backend/domain/raffle/controller/PrizeController.java
  backend/src/main/java/com/passtival/backend/domain/raffle/controller/RaffleController.java
Labels: 👨🏻‍💻준선, 🛠️ Refactor, 🥇 높음
