Repository Passtival/Passtival-server, pull requests merged in 2025-09, with the labels that each got.

#97 Refactor: auth 폴더 개선 #96
  backend/src/main/java/com/passtival/backend/domain/admin/controller/AdminAuthController.java
  backend/src/main/java/com/passtival/backend/domain/admin/service/AdminAuthService.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MatchingApplicantController.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/MatchingController.java
  backend/src/main/java/com/passtival/backend/domain/matching/controller/test/AuthTestController.java
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/passtival/backend/global/handler/CustomAuthenticationFailureHandler.java
  backend/src/main/java/com/passtival/backend/global/handler/OAuth2SuccessHandler.java
  backend/src/main/java/com/passtival/backend/global/security/controller/TokenController.java
  backend/src/main/java/com/passtival/backend/global/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/passtival/backend/global/security/filter/LoginFilter.java
  backend/src/main/java/com/passtival/backend/global/security/model/AuthUserDto.java
  backend/src/main/java/com/passtival/backend/global/security/model/CustomMemberDetails.java
  backend/src/main/java/com/passtival/backend/global/security/model/CustomOAuth2User.java
  backend/src/main/java/com/passtival/backend/global/security/model/KakaoResponse.java
  backend/src/main/java/com/passtival/backend/global/security/model/Oauth2Response.java
  backend/src/main/java/com/passtival/backend/global/security/model/token/RefreshTokenRequest.java
  backend/src/main/java/com/passtival/backend/global/security/model/token/TokenResponse.java
  backend/src/main/java/com/passtival/backend/global/security/service/CustomMemberDetailsService.java
  backend/src/main/java/com/passtival/backend/global/security/service/CustomOAuth2UserService.java
  backend/src/main/java/com/passtival/backend/global/security/service/TokenService.java
  backend/src/main/java/com/passtival/backend/global/security/util/JwtUtil.java
  backend/src/main/java/com/passtival/backend/global/security/util/ResponseUtil.java
Labels: 👨🏻‍💻준선, 🛠️ Refactor

#109 Feat: nginx 프록시 설정, 바인딩 설정 #107
  backend/docker-compose.dev.yml
  backend/docker-compose.prod.yml
  backend/src/main/resources/application-prod.yml
Labels: ✨ Feature, 👨🏻‍💻준선

#115 refactor: accrss Token 발급시 요청 형태 변경
  backend/src/main/java/com/passtival/backend/global/common/BaseResponseStatus.java
  backend/src/main/java/com/passtival/backend/global/security/controller/TokenController.java
  backend/src/main/java/com/passtival/backend/global/security/model/token/RefreshTokenRequest.java
  backend/src/main/java/com/passtival/backend/global/security/service/TokenService.java
Labels: 👨🏻‍💻 원진, 🛠️ Refactor, 🥈 보통

#121 Redis 제거, 배포환경 RDS 연동
  backend/.env.example
  backend/build.gradle
  backend/docker-compose.dev.yml
  backend/src/main/resources/application-dev.yml
Labels: ⚙️ Setting, 👨🏻‍💻준선

#123 refactor: 로그인 이후에 프론트 서버로 토큰을 발급 받은 후 콜백 #116
  backend/docker-compose.prod.yml
  backend/src/main/java/com/passtival/backend/global/handler/OAuth2SuccessHandler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 👨🏻‍💻 원진, 🛠️ Refactor, 🥇 높음

#127 menu응답 값 id추가
  backend/src/main/java/com/passtival/backend/domain/festival/menu/model/response/MenuResponse.java
Labels: 👨🏻‍💻 재상, 🛠️ Refactor

#136 feat: 스캔 봇 차단 #135
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
Labels: ✨ Feature, 👨🏻‍💻 원진, 🥉낮음

#141 fix: 컨트롤러에서 리다이렉트 시키는 방식으로 해결 #135
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/passtival/backend/global/security/controller/BlockController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🐛 Bug, 👨🏻‍💻 원진, 🛠️ Refactor, 🥇 높음

#143 refactor: 운영환경 Docker-compose.prod Redis, MySQL 제거 #142
  backend/docker-compose.prod.yml
Labels: 👨🏻‍💻준선, 🛠️ Refactor, 🥈 보통

#156 [Chore] 브랜치, PR, Issue 컨벤션, 템플릿 개선과 깃허브 문서화 개선합니다.
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/REFACTOR_REQUEST.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/help.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📌 Chore

#176 feat: Level-up 시 Valid 유효성 검증
  backend/src/main/java/com/passtival/backend/domain/member/model/entity/request/LevelUpRequest.java
Labels: 🐛 Bug

#186 refactor: 번호팅 계정 조회 시 신청 유무를 함께 전달 하도록 수정
  backend/src/main/java/com/passtival/backend/domain/matching/model/response/MatchingApplicantResponse.java
  backend/src/main/java/com/passtival/backend/domain/matching/service/MatchingApplicantService.java
Labels: 🛠️ Refactor

#195 [Refactor] 부스 커서 정령 오름차순
  backend/src/main/java/com/passtival/backend/domain/festival/booth/repository/BoothRepository.java
Labels: 🛠️ Refactor

#197 refctor: 매칭 스케줄러 .env를 참고하는 방식으로 수정
  backend/docker-compose.dev.yml
  backend/docker-compose.prod.yml
  backend/src/main/java/com/passtival/backend/domain/matching/service/MatchingScheduler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🛠️ Refactor

#205 [Feat] 공연 시간순 정렬
  backend/src/main/java/com/passtival/backend/domain/festival/performance/controller/PerformanceController.java
  backend/src/main/java/com/passtival/backend/domain/festival/performance/service/PerformanceService.java
Labels: ✨ Feature

#210 fix: 소셜 로그인 실패 문제 해결
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/passtival/backend/global/handler/CustomAuthenticationFailureHandler.java
Labels: 🐛 Bug

#212 refactor: Prometheus 제거
  backend/build.gradle
  backend/docker-compose.dev.yml
  backend/docker-compose.prod.yml
  backend/prometheus.dev.yml
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/passtival/backend/global/health/CpuHealth.java
  backend/src/main/java/com/passtival/backend/global/health/MemoryHealth.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🛠️ Refactor

#217 refactor: 스웨거, Test컨트롤러 권한 수정
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
Labels: 🛠️ Refactor

#221 [Feat] 부스 위치id 속성 추가
  backend/src/main/java/com/passtival/backend/domain/festival/booth/controller/BoothController.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/entity/Booth.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothDetailResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/model/response/BoothResponse.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/repository/BoothRepository.java
  backend/src/main/java/com/passtival/backend/domain/festival/booth/service/BoothService.java
Labels: ✨ Feature

#229 refactor: 운영환경 Docker-compose.prod MySQL 추가
  backend/docker-compose.prod.yml
  backend/src/main/java/com/passtival/backend/global/config/SecurityConfig.java
  backend/src/main/resources/application-prod.yml
Labels: 🛠️ Refactor
